name: Continuous Check

on: [push]

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build 'jvm' with Gradle
        run: ./code/jvm/gradlew -p code/jvm check
      - name: Build `tic-tac-toe` with Gradle
        env:
           DB_URL: ${{ secrets.DB_URL }}
        run: ./code/tic-tac-toe/gradlew -p code/tic-tac-toe check